name: Build, Push Docker Image, and Deploy to WSL



on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-actions-demo:latest

  deploy-to-wsl:
    needs: docker-build-push
    runs-on: self-hosted
    steps:
      - name: Deploy to WSL
        uses: appleboy/ssh-action@v1.0.3  # Critical: Use v1.0.3+ for reliability
        with:
          host: ${{ secrets.SSH_HOST }}  # Your WSL IP (172.24.11.107)
          username: ${{ secrets.SSH_USER }}  # "vee"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Clean up old container
            docker stop fastapi-demo || true
            docker rm fastapi-demo || true
            
            # Pull and run new image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-actions-demo:latest
            docker run -d \
              --name fastapi-demo \
              -p 8000:8000 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-actions-demo:latest
            
            # Verify deployment
            echo "Deployment successful!"
            docker ps | grep fastapi-demo
