name: Build, Push Docker Image, and Deploy to WSL

on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-actions-demo:latest

  deploy-to-wsl:
    needs: docker-build-push
    runs-on: self-hosted
    steps:
      - name: Verify Docker is running
        run: docker ps
        shell: bash
        
      - name: Deploy to WSL
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-actions-demo:latest
        run: |
          # Stop and remove old container if exists
          if [ "$(docker ps -aq -f name=fastapi-demo)" ]; then
            docker stop fastapi-demo
            docker rm fastapi-demo
          fi
          
          # Pull the new image
          docker pull $DOCKER_IMAGE
          
          # Run new container
          docker run -d \
            --name fastapi-demo \
            -p 8000:8000 \
            --restart unless-stopped \
            $DOCKER_IMAGE
          
          # Health check
          echo "Waiting for container to start..."
          sleep 10
          docker ps
          curl -s http://localhost:8000 || echo "Health check failed but continuing"
          
          echo "🚀 Deployment successful!"
